public enum WorldFeatureVariant
{
    None,
    MapleTree,
    SugarMapleTree,
    BirchAspenTree,
    BeechTree,
    SpruceTree,
    WhitePineTree,
    OakTree,
    BlueberryBush,
    RaspberryBush,
    StrawberryBush,
    BlackberryBush,
    Boulder,
    GrasslandMapleTree,
    GrasslandBirchAspenTree,
    GrasslandWhitePineTree,
    GrasslandOakTree,
    GrasslandBoulder,
    GrasslandWillowTree,
    GrasslandLargeBoulder
}
